version: '3.8'

services:
  tests:
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "mvn clean test &&
             allure generate target/allure-results -o target/allure-report &&
             allure open target/allure-report"
    ports:
      - "4040:4040"